import { createSlice } from "@reduxjs/toolkit";

// Create a Redux slice for managing projects
export const projectsSlice = createSlice({
  name: "projects",

  // Set the initial state
  initialState: {
    projects: [],
  },

  // Define reducers for updating the state
  reducers: {
    // Reducer for populating the projects array
    populateArray: (state, action) => {
      state.projects = action.payload;
    },
  },
});

// Extract the actions generated by the projects slice
export const { populateArray } = projectsSlice.actions;

// Export the projects reducer
export default projectsSlice.reducer;
