import { createSlice } from "@reduxjs/toolkit";

// Create a Redux slice for managing the screen state
export const screenSlice = createSlice({
  name: "screen",

  // Set the initial state
  initialState: {
    screen: "projects",
  },

  // Define reducers for updating the state
  reducers: {
    // Reducer for updating the current screen
    updateScreen: (state, action) => {
      state.screen = action.payload;
    },

    // Reducer for resetting the screen to the default view
    resetScreen: (state) => {
      state.screen = "projects";
    },
  },
});

// Extract the actions generated by the screen slice
export const { updateScreen, resetScreen } = screenSlice.actions;

// Export the screen reducer
export default screenSlice.reducer;
