import { createSlice } from "@reduxjs/toolkit";

// Create a Redux slice for managing the update state
export const updateSlice = createSlice({
  name: "update",

  // Set the initial state
  initialState: {
    projectId: "",
  },

  // Define reducers for updating the state
  reducers: {
    // Reducer for assigning the project ID
    assignProjectId: (state, action) => {
      state.projectId = action.payload;
    },
  },
});

// Extract the action generated by the update slice
export const { assignProjectId } = updateSlice.actions;

// Export the update reducer
export default updateSlice.reducer;
